### ISSUE TITLE
I got a DB error, miner can't work

### ISSUE THREAD

**Issue by yuanaichi** [tellor-io/telliot#473]
I got a DB error, miner can not work.

panic: write db/chunks_head/000112: file already closed

goroutine 251 [running]:
github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc0000db0a0, 0xc000177500)
        /home/parallels/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210520210015-1838068db5df/tsdb/head.go:2322 +0x21a
github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk(0xc0000db0a0, 0x17a90b80034, 0xc000177500, 0x0)
        /home/parallels/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210520210015-1838068db5df/tsdb/head.go:2293 +0x39
github.com/prometheus/prometheus/tsdb.(*memSeries).append(0xc0000db0a0, 0x17a90b80034, 0x421bf08eb0000000, 0x1db192, 0xc000177500, 0x0)
        /home/parallels/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210520210015-1838068db5df/tsdb/head.go:2449 +0x38e
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0xc013ee1130, 0x0, 0x0)
        /home/parallels/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210520210015-1838068db5df/tsdb/head.go:1503 +0x525
github.com/prometheus/prometheus/tsdb.dbAppender.Commit(0x172adc0, 0xc013ee1130, 0xc000272000, 0xc001fc5c98, 0x4e5565)
        /home/parallels/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210520210015-1838068db5df/tsdb/db.go:818 +0x35
github.com/tellor-io/telliot/pkg/tracker/index.(*IndexTracker).recordInterval.func1(0xc001fc5e28, 0x172b8c0, 0xc015f9ce40, 0x17090c0, 0xc0011650b0)
        /media/psf/Home/go/src/github.com/tellor-io/telliot/pkg/tracker/index/index.go:254 +0x1c2
github.com/tellor-io/telliot/pkg/tracker/index.(*IndexTracker).recordInterval(0xc0001d2460, 0x17090c0, 0xc0011650b0, 0x17a90b80034, 0x6fc23ac00, 0xc0005847d0, 0x7, 0x1724400, 0xc000b84ae0, 0x0, ...)
        /media/psf/Home/go/src/github.com/tellor-io/telliot/pkg/tracker/index/index.go:273 +0x4d6
github.com/tellor-io/telliot/pkg/tracker/index.(*IndexTracker).record(0xc0001d2460, 0xf5de81400, 0xc0005847d0, 0x7, 0x6fc23ac00, 0x1724400, 0xc000b84ae0)
        /media/psf/Home/go/src/github.com/tellor-io/telliot/pkg/tracker/index/index.go:223 +0x425
created by github.com/tellor-io/telliot/pkg/tracker/index.(*IndexTracker).Run
        /media/psf/Home/go/src/github.com/tellor-io/telliot/pkg/tracker/index/index.go:193 +0x139

    The official Tellor cli tool  ()
    -----------------------------------------
        Website: https://tellor.io
        Github:  https://github.com/tellor-io/telliot
telliot: error: creating tsdb DB: reloadBlocks: invalid block sequence: block time ranges overlap: [mint: 1625752800162, maxt: 1625760000000, range: 1h59m59s, blocks: 3]: <ulid: 01FA3HCYEZ931ZQZWCK7XKT93K, mint: 1625752800162, maxt: 1625760000000, range: 1h59m59s>, <ulid: 01FA41KH8MH5G7QN7J9GJ3FDNM, mint: 1625752800162, maxt: 1625760000000, range: 1h59m59s>, <ulid: 01FA44H6EV38JCB01RT6P1P0KX, mint: 1625752800162, maxt: 1625760000000, range: 1h59m59s>

**Comment by krasi-georgiev** [comment]
this usually happens if you run more than one instance writing to the same DB folder. Make sure that only one telliot uses this folder. If you run telliot in mining and dataserver mode need to make sure that they have their own DB folder.
